name: env17
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - jupyterlab
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - pip:
      - tensorflow==2.17  # or 2.17 if needed
      - keras-nightly  # Only needed if using TensorFlow 2.17